### PR TITLE
Make it easier to use background_area.gd

### PR DESCRIPTION
**Pull request by fleskesvor**
This is the stuff in https://github.com/godotengine/escoria/pull/19, though with changes to support two-click actions. I've also made some changes to the test scene to demonstrate the functionality, but that's not working 100% right now.

Shouldn't break any functionality though, and makes it much easier to use an Area2D instead of a TextureFrame for background input. Just make sure that the background texture frame isn't capturing input.

### CODE REVIEW

**Comment by fleskesvor** [comment]
The last commit fixes interaction with the mountain. I forgot to set an interaction point for it.

**Comment by JenniBee** [comment]
I'm checking this out now.

**Comment by JenniBee** [comment]
I see in the Escoria commit that there is issues with player movement, but as you said it's not working 100% right now.  I played through the clock memory and the doug memory, and since it's relegated now to the test room and it didn't seem to break anything, I'll go ahead and merge this for now. :)

**Comment by fleskesvor** [comment]
Thanks, Jenni. :) 

Yeah, it's only in the test room for now. I've also used those new scripts in the Oasis/Wizard room, but I'll try to sort out the issue before that's merged, unless the Escoria developers beat me to it.

**Pull request merged**
