### PR TITLE
"UI_NEW_GAME_CONFIRM" -> "NEW GAME CONFIRMATION"

### PR DESCRIPTION
**Pull request by ghost**
#41 Underscores are not being converted to spaces.

### CODE REVIEW

**Comment by ghost** [comment]
I'd rather identify how to intigrate these labels to the language translations. Checked that both iterations fail to translate as is. If you can help me identify the structure around the UI confirm_popup.start it seems this is a unique case and the credits are a unique case aswell, as the quit modal works as needed.

**Comment by Cheeseness** [comment]
UI_NEW_GAME_CONFIRM is an identifier for a string that should get localised. This isn't the right place to make this change.

Unfortunately, I'm pressed for time at the moment and can't look up the best approach.

**Comment by ghost** [comment]
I see that, I'd much rather identify the location of this particular label and figure out what was happening to that first parameter. If you know where that is, I'm hunting.

**Review by ghost — COMMENTED** [review]
Swing and a miss, wrong file. I had meant another file... opening_menu.gd

**Comment by fleskesvor** [comment]
If you open `ui/main_menu.tscn` and look at the text of the Button nodes and how `TranslationServer` is being used in the attached script, `ui/main_menu.gd`, you'll get a better understanding of how this stuff works in Godot. I've written some advice on how to do the proper rigging to get it to work in #41.

**Pull request closed without merging**
